#!/bin/bash

###############################################################################
# Fluho
# Installer
#
# Written by Juan Jose Castro Sotelo
# Licensed under terms of GPLv3
#
###############################################################################




DESTDIR_DFL="/opt/fluho"  # Application installation dir inside rootfs
ROOTDIR_DFL=""  # Rootfs path (for deb building, jails). Empty is equal to /




exitIfNotRoot() {
  if [ $EUID -ne 0 ]; then
     echo "\
This script must be run as root or with sudo.

Example: 

    $ sudo ${0##*/}" 1>&2
     exit 1
  fi
}


show_usage()
{
  echo "\
Usage: ${0##*/} <options>"
}


show_help()
{
  echo "\
Install the application in the operating system
[options]
  -d, --destdir DIR
    Target directory where the application will be installed
    Default: $DESTDIR_DFL
  -r, --root DIR
    Set the root path of the operating system file system.
    For example, /etc/environment will be searched in {DIR}/etc/environment
    Default: ${ROOTDIR_DFL:-/}
  -u, --uninstall
    Uninstall the application from the operating system.
  -h, --help
    Show this information"
}


show_option_error()
{
  echo "\
Bad action, option or argument. Take a look at:

    $ ${0##*/} --help" >&2
}




do_install()
{
  ROOTDIR="${ROOTDIR:-$ROOTDIR_DFL}"
  DESTDIR="${DESTDIR:-$DESTDIR_DFL}"
  
  [ "$ROOTDIR" != "" ] && ROOTDIR="${ROOTDIR}/"  # Get sure ROOTDIR ends with /
  
  mkdir -p "${ROOTDIR}${DESTDIR}" && \
  install -v --mode=774 fluho          "${ROOTDIR}${DESTDIR}" && \
  install -v --mode=664 fluho.user     "${ROOTDIR}${DESTDIR}" && \
  install -v --mode=664 fluho-ctr      "${ROOTDIR}${DESTDIR}" && \
  install -v --mode=664 fluho-mdl      "${ROOTDIR}${DESTDIR}" && \
  install -v --mode=664 fluho-mdl-git  "${ROOTDIR}${DESTDIR}" && \

  sed -i "\%^PATH=${DESTDIR}:.*%d" "${ROOTDIR}/etc/environment" && \
  echo "PATH=${DESTDIR}:${PATH}" >> "${ROOTDIR}/etc/environment" && \
  echo "Success" || echo "Error"
}


do_uninstall()
{
  ROOTDIR="${ROOTDIR:-$ROOTDIR_DFL}"
  #DESTDIR="${DESTDIR:-$DESTDIR_DFL}"

  [ "$ROOTDIR" != "" ] && ROOTDIR="${ROOTDIR}/"  # Get sure ROOTDIR ends with /

  if [ "$DESTDIR" == "" ]; then
    whichpath="`which fluho`"
  fi

  if [ "$whichpath" != "" ]; then
    DESTDIR="$whichpath"
  else
    DESTDIR="$DESTDIR_DFL"
  fi
  
  echo "Uninstalling fluho at ${ROOTDIR}${DESTDIR}"

  rm -vf "${ROOTDIR}${DESTDIR}/fluho" && \
  rm -vf "${ROOTDIR}${DESTDIR}/fluho.user" && \
  rm -vf "${ROOTDIR}${DESTDIR}/fluho-ctr" && \
  rm -vf "${ROOTDIR}${DESTDIR}/fluho-mdl" && \
  rm -vf "${ROOTDIR}${DESTDIR}/fluho-mdl-git" && \
  
  sed -i "\%^PATH=${DESTDIR}:.*%d" "${ROOTDIR}/etc/environment" && \
  rmdir -v --ignore-fail-on-non-empty "${ROOTDIR}${DESTDIR}/" && \
  echo "Success" || echo "Error"
}





main()
{
  DESTDIR=""
  ROOTDIR=""
  OPTUNINSTALL=false
  
  
  SHORT_OPTS=":d:r:uh"
  LONG_OPTS="destdir:,root:,uninstall,help"
  args=`getopt -o $SHORT_OPTS --long $LONG_OPTS -- "$@"`
  if [ $? -ne 0 ]; then
    show_option_error
    exit 1
  fi
  eval set -- "$args"


  while true ; do
    case "$1" in
      --destdir | -d )  shift
                        DESTDIR="$1"
                        ;;
      --rootdir | -r )  shift
                        ROOTDIR="$1"
                        ;;
      --uninstall | -u ) 
                        OPTUNINSTALL=true
                        ;;
      --help | -h )     show_help; exit 0
                        ;;
      --)               shift ; break
                        ;;
      *)                echo "Internal error ($1)!" ; exit 1
    esac
    shift
  done


  exitIfNotRoot

  if [ "$OPTUNINSTALL" == true ]; then
    do_uninstall
  else
    do_install
  fi

}


main "$@"
